### ISSUE TITLE
Looking for more information.

### ISSUE THREAD

**Issue by veryfungi** [jwayneroth/teensy-wave-machine#1]
Sorry for this method of contact, recommended by a member of the teensy forum. I have a couple teensy 3.1's and would love to recreate your synth. Do you have audio examples of the sound, and any other information that would help me get going? Thanks in advance!

**Comment by jwayneroth** [comment]
I don't have any audio samples. I can tell you that the code expects 4
pots, 4 buttons and an oled display in addition to the Audio Adaptor and
Teensy. You should be able to comment out the display and maybe some of the
button code if you just want to hear something. But the audio was all
generated using Paul's Audio Library, so his samples should give you a
sense of what's possible. The project was mostly focused on the layering of
4 noise signals with a visual display. If you're still interested, I may be
able to take some pictures/video later in the week.

**Comment by veryfungi** [comment]
Hi Jonathan, 
I am new to modular synthesizers and am mostly interested in creating generative ambient sounds. The word drone in the description caught my search requests. I am going to try and recreate your projects and would love to see or hear anything you can provide. My electronics skills are top notch, my programming, not so much. I will struggle with that. :) 
Thanks so much, 
Jim
ps would you prefer e-mail?

**Comment by jwayneroth** [comment]
I updated the readme with images and a link to a video walk-through. Hopefully that helps. Best.
